version: '3'

services:
  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    restart: no
    env_file:
      - ./envs/server.env
  client:
    build:
      context: ./client
    restart: no
    env_file:
      - ./envs/client.env
    depends_on:
      - server


